import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Iframe(),
        ]),
      ),
    );
  }
}

class Iframe extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1760,
          height: 1016,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 103.51,
                top: 94.46,
                child: Container(
                  width: 477.33,
                  height: 392,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 2, color: Color(0x99E5E7EB)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2,
                        top: 2,
                        child: Container(
                          width: 473.33,
                          height: 192,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/473x192"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 218,
                        child: SizedBox(
                          width: 74.92,
                          height: 16,
                          child: Text(
                            'CATEGORY',
                            style: TextStyle(
                              color: Color(0xFF9CA3AF),
                              fontSize: 12,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w500,
                              height: 0.11,
                              letterSpacing: 1.20,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 238,
                        child: SizedBox(
                          width: 111.14,
                          height: 28,
                          child: Text(
                            'The Catalyzer',
                            style: TextStyle(
                              color: Color(0xFF111827),
                              fontSize: 18,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w500,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 283,
                        child: SizedBox(
                          width: 387.50,
                          height: 42,
                          child: Text(
                            'Photo booth fam kinfolk cold-pressed sriracha leggings\njianbing microdosing tousled waistcoat.',
                            style: TextStyle(
                              color: Color(0xFF4B5563),
                              fontSize: 15.75,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.10,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 342,
                        child: SizedBox(
                          width: 81.56,
                          height: 24,
                          child: Text(
                            'Learn More',
                            style: TextStyle(
                              color: Color(0xFF6366F1),
                              fontSize: 16,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 115.36,
                        top: 346,
                        child: Container(
                          width: 16,
                          height: 16,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 348.72,
                        top: 342,
                        child: Container(
                          padding: const EdgeInsets.only(top: 4, right: 13.80, bottom: 4),
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0xFFE5E7EB)),
                              top: BorderSide(color: Color(0xFFE5E7EB)),
                              right: BorderSide(width: 2, color: Color(0xFFE5E7EB)),
                              bottom: BorderSide(color: Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: 16,
                                height: 16,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                  ],
                                ),
                              ),
                              const SizedBox(width: 4),
                              SizedBox(
                                width: 29.01,
                                height: 14,
                                child: Text(
                                  '1.2K',
                                  style: TextStyle(
                                    color: Color(0xFF9CA3AF),
                                    fontSize: 14,
                                    fontFamily: 'Roboto',
                                    fontWeight: FontWeight.w400,
                                    height: 0.07,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 423.53,
                        top: 346,
                        child: Container(
                          width: 16,
                          height: 16,
                          padding: const EdgeInsets.all(2),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 443.53,
                        top: 347,
                        child: SizedBox(
                          width: 8,
                          height: 14,
                          child: Text(
                            '6',
                            style: TextStyle(
                              color: Color(0xFF9CA3AF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.07,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 641.33,
                top: 96,
                child: Container(
                  width: 477.33,
                  height: 392,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 2, color: Color(0x99E5E7EB)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2,
                        top: 2,
                        child: Container(
                          width: 473.33,
                          height: 192,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/473x192"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 218,
                        child: SizedBox(
                          width: 74.92,
                          height: 16,
                          child: Text(
                            'CATEGORY',
                            style: TextStyle(
                              color: Color(0xFF9CA3AF),
                              fontSize: 12,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w500,
                              height: 0.11,
                              letterSpacing: 1.20,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 238,
                        child: SizedBox(
                          width: 118.86,
                          height: 28,
                          child: Text(
                            'The 400 Blows',
                            style: TextStyle(
                              color: Color(0xFF111827),
                              fontSize: 17.86,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w500,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 283,
                        child: SizedBox(
                          width: 387.50,
                          height: 42,
                          child: Text(
                            'Photo booth fam kinfolk cold-pressed sriracha leggings\njianbing microdosing tousled waistcoat.',
                            style: TextStyle(
                              color: Color(0xFF4B5563),
                              fontSize: 15.75,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.10,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 342,
                        child: SizedBox(
                          width: 81.56,
                          height: 24,
                          child: Text(
                            'Learn More',
                            style: TextStyle(
                              color: Color(0xFF6366F1),
                              fontSize: 16,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 115.36,
                        top: 346,
                        child: Container(
                          width: 16,
                          height: 16,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 348.72,
                        top: 342,
                        child: Container(
                          padding: const EdgeInsets.only(top: 4, right: 13.80, bottom: 4),
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0xFFE5E7EB)),
                              top: BorderSide(color: Color(0xFFE5E7EB)),
                              right: BorderSide(width: 2, color: Color(0xFFE5E7EB)),
                              bottom: BorderSide(color: Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: 16,
                                height: 16,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                  ],
                                ),
                              ),
                              const SizedBox(width: 4),
                              SizedBox(
                                width: 29.01,
                                height: 14,
                                child: Text(
                                  '1.2K',
                                  style: TextStyle(
                                    color: Color(0xFF9CA3AF),
                                    fontSize: 14,
                                    fontFamily: 'Roboto',
                                    fontWeight: FontWeight.w400,
                                    height: 0.07,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 423.53,
                        top: 346,
                        child: Container(
                          width: 16,
                          height: 16,
                          padding: const EdgeInsets.all(2),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                     
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 443.53,
                        top: 347,
                        child: SizedBox(
                          width: 8,
                          height: 14,
                          child: Text(
                            '6',
                            style: TextStyle(
                              color: Color(0xFF9CA3AF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.07,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1150.66,
                top: 96,
                child: Container(
                  width: 477.33,
                  height: 392,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 2, color: Color(0x99E5E7EB)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2,
                        top: 2,
                        child: Container(
                          width: 473.33,
                          height: 192,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/473x192"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 218,
                        child: SizedBox(
                          width: 74.92,
                          height: 16,
                          child: Text(
                            'CATEGORY',
                            style: TextStyle(
                              color: Color(0xFF9CA3AF),
                              fontSize: 12,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w500,
                              height: 0.11,
                              letterSpacing: 1.20,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 238,
                        child: SizedBox(
                          width: 117.90,
                          height: 28,
                          child: Text(
                            'Shooting Stars',
                            style: TextStyle(
                              color: Color(0xFF111827),
                              fontSize: 17.72,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w500,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 283,
                        child: SizedBox(
                          width: 387.49,
                          height: 42,
                          child: Text(
                            'Photo booth fam kinfolk cold-pressed sriracha leggings\njianbing microdosing tousled waistcoat.',
                            style: TextStyle(
                              color: Color(0xFF4B5563),
                              fontSize: 15.75,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.10,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 342,
                        child: SizedBox(
                          width: 81.56,
                          height: 24,
                          child: Text(
                            'Learn More',
                            style: TextStyle(
                              color: Color(0xFF6366F1),
                              fontSize: 16,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 115.36,
                        top: 346,
                        child: Container(
                          width: 16,
                          height: 16,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: [
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 348.72,
                        top: 342,
                        child: Container(
                          padding: const EdgeInsets.only(top: 4, right: 13.80, bottom: 4),
                          decoration: BoxDecoration(
                            border: Border(
                              left: BorderSide(color: Color(0xFFE5E7EB)),
                              top: BorderSide(color: Color(0xFFE5E7EB)),
                              right: BorderSide(width: 2, color: Color(0xFFE5E7EB)),
                              bottom: BorderSide(color: Color(0xFFE5E7EB)),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: 16,
                                height: 16,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                  ],
                                ),
                              ),
                              const SizedBox(width: 4),
                              SizedBox(
                                width: 29.01,
                                height: 14,
                                child: Text(
                                  '1.2K',
                                  style: TextStyle(
                                    color: Color(0xFF9CA3AF),
                                    fontSize: 14,
                                    fontFamily: 'Roboto',
                                    fontWeight: FontWeight.w400,
                                    height: 0.07,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 423.53,
                        top: 346,
                        child: Container(
                          width: 16,
                          height: 16,
                          padding: const EdgeInsets.all(2),
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                          
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 443.53,
                        top: 347,
                        child: SizedBox(
                          width: 8,
                          height: 14,
                          child: Text(
                            '6',
                            style: TextStyle(
                              color: Color(0xFF9CA3AF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 0.07,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}